language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"

before_install:
    - sudo apt-get update

install:
    - pip install pipenv
    - pipenv install

script:
    - pipenv shell
    - flask run
